crm/routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

// Admins routes
require_once ('crm\admin.php');
// Team leader routes
require_once ('crm\teamleader.php');
// Sales routes
require_once ('crm\sales.php');
Route::resource('/users', 'UserController');


// Errors
Route::get('/403', function () {
    return view('errors.403');
})->name('403');

crm/resources/views/layouts/sub-views/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer navbar-light " >
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2018 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

@section('js')
    <!-- jQuery -->
    <script src="{{ asset('backoffice/plugins/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('backoffice/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('backoffice/dist/js/adminlte.min.js') }}"></script>
@show
</body>
</html>

crm/resources/views/layouts/sub-views/header.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>CRM | @yield('title')</title>

@section('css')
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('backoffice/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('backoffice/dist/css/adminlte.min.css') }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
@show
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-light  border-bottom">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            <i class="nav-icon fas fa-home" style="padding-top: 14px;"></i>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{{ route('home') }}" class="nav-link ">Home</a>
            </li>
            <i class="nav-icon fas fa-phone-square" style="padding-top: 14px;"></i>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
            </li>
        </ul>

        <!-- SEARCH FORM -->
        <form class="form-inline ml-3">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{{ asset('backoffice/dist/img/user1-128x128.jpg') }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">Call me whenever you can...</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="backoffice/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">I got your message bro</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="backoffice/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">The subject goes here</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf

                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </nav>
    <!-- /.navbar -->

crm/resources/views/layouts/sub-views/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-danger elevation-4" style="background:#004a99">
    <!-- Brand Logo -->
    <a href="{{ route('home') }}" class="brand-link">
        <i class="nav-icon fas fa-business-time"></i>
        <span class="brand-text font-weight-light">CRM</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview menu-open">
                    @if(Auth::user()->role->slug=='ADM'||Auth::user()->role->slug=='TMLD')
                        <a href="#" class="nav-link {{ Request::is('leads*') ? 'active': ''}}">
                        <i class="nav-icon fas fa-chess-king"></i>
                        <p>
                            Leaders
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    @endif
                    @if(Auth::user()->role->slug=='SAL')
                        <a href="#" class="nav-link {{ Request::is('lead*') ? 'active': ''}}">
                        <i class="nav-icon fas fa-chess-king"></i>
                        <p>
                            Leaders
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    @endif

                    <ul class="nav nav-treeview">
                        @if (Auth::user()->role->slug == 'ADM')
                            <li class="nav-item">
                                <a href="{{ route('leads.create') }}" class="nav-link {{ Request::is('leads/create') ? 'active': ''}}">
                                    <i class="far fa-check-circle nav-icon"></i>
                                    <p>New Lead</p>
                                </a>
                            </li>
                        @endif
                        @if (Auth::user()->role->slug == 'ADM' || Auth::user()->role->slug == 'TMLD')
                            <li class="nav-item">
                                <a href="{{ route('leads.index') }}" class="nav-link {{ Request::is('leads') ? 'active': ''}}">
                                    <i class="far fa-check-circle nav-icon"></i>
                                    <p>All Leads</p>
                                </a>
                            </li>
                        @elseif(Auth::user()->role->slug == 'SAL')
                                <li class="nav-item">
                                    <a href="{{ route('sales.index') }}" class="nav-link {{ Request::is('lead/my_lead') ? 'active': ''}}">
                                        <i class="far fa-check-circle nav-icon"></i>
                                        <p>My Leaders</p>
                                    </a>
                                </li>
                        @endif
                    </ul>
                </li>
                @if(Auth::user()->role->slug=='ADM')

                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link {{ Request::is('users*') ? 'active': ''}}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Users
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('users.create')}}" class="nav-link {{ Request::is('users/create') ? 'active': ''}}">
                                <i class="far fa-check-circle nav-icon"></i>
                                <p>New User</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('users.index')}}" class="nav-link {{ Request::is('users') ? 'active': ''}}">
                                <i class="far fa-check-circle nav-icon"></i>
                                <p>All Users</p>
                            </a>
                        </li>
                    </ul>
                </li>
                @endif
                @if (Auth::user()->role->slug == 'ADM'
                    || Auth::user()->role->slug == 'TMLD'
                    || Auth::user()->role->slug == 'SAL')
                    <li class="nav-item has-treeview menu-open">
                       @if(Auth::user()->role->slug=='ADM'||Auth::user()->role->slug=='TMLD')
                         <a href="#" class="nav-link {{ Request::is('calls*') ? 'active': ''}}">
                            <i class="nav-icon fas fa-phone-alt"></i>
                            <p>
                                Calls
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        @endif
                           @if(Auth::user()->role->slug=='SAL')
                               <a href="#" class="nav-link {{ Request::is('call*') ? 'active': ''}}">
                                   <i class="nav-icon fas fa-phone-alt"></i>
                                   <p>
                                       Calls
                                       <i class="right fas fa-angle-left"></i>
                                   </p>
                               </a>
                            @endif
                               <ul class="nav nav-treeview">
                            <li class="nav-item">
                            @if(Auth::user()->role->slug=='ADM'||Auth::user()->role->slug=='TMLD')
                                    <a href="{{route('calls.view')}}" class="nav-link {{ Request::is('calls*') ? 'active': ''}}">
                                    <i class="far fa-check-circle nav-icon"></i>
                                    <p>All calls</p>
                                </a>
                            @endif
                            @if(Auth::user()->role->slug=='SAL')
                                <a href="{{route('sales.view')}}" class="nav-link {{ Request::is('call/my_calls') ? 'active': ''}}">
                                    <i class="far fa-check-circle nav-icon"></i>
                                    <p>My calls</p>
                                </a>
                            @endif
                            </li>
                        </ul>
                    </li>
                    @endif
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>