crm/routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

// Admins routes
require_once ('crm\admin.php');
// Team leader routes
require_once ('crm\teamleader.php');
// Sales routes
require_once ('crm\sales.php');
Route::resource('/users', 'UserController');


// Errors
Route::get('/403', function () {
    return view('errors.403');
})->name('403');

crm/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class, 'role_id');
    }

    public function leads()
    {
        return $this->hasMany(Lead::class, 'sales_id');
    }

    public static function getAllSales()
    {
        $salesRole = Role::where('slug', 'SAL')
            ->first()
        ;

        return self::where('role_id', $salesRole->id)->get();
    }

    public function call()
    {
        return $this->hasMany(Call::class,'user_id');
    }
}

crm/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    public function index()
    {   $users=User::where('status',1)->orderBy('name')->paginate(10);
        return view('backoffice.users.index',
            ['users'=>$users]);
    }

    public function create()
    {
        return view('backoffice.users.create');
    }

    public function store(UserRequest $request)
    {
        $user=new User();
        $user->name=$request->input('name');
        $user->password=Hash::make($request->input('password'));
        $user->email=$request->input('email');
        $user->role_id=$request->input('permission');
        $user->save();
        return redirect()->route('users.index');
    }
    public function show(User $user)
    {
        return view('backoffice.users.show', ['user'=> $user]);
    }
    public function edit(User $user)
    {
        return view('backoffice.users.edit', ['user'=>$user]);
    }
    public function update(Request $request, User $user)
    {

        $validator = Validator::make($request->all(), [
            'name'=> 'required|string',
            'email'=> [
                'email',
                Rule::unique('users')->ignore($user),
            ]
        ]);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator);
        }

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->role_id = $request->input('permission');

        $user->save();
        return redirect()->route('users.show', $user);
    }
    public function destroy(User $user)
    {    $user->status = false;
        $user->save();
        return redirect()->route('users.index')->with('message', 'Deleted');
    }

}

crm/resources/views/backoffice/users/create.blade.php
@extends('layouts.app')
@section('title','Create User')
@section('pageHeader','Create Users')
@section('content')

    <form action="{{route('users.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" id="name" >
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="email" id="email" >
        </div>
        <div class="form-group">
            <label for="permission">Permission</label>
            <select name="permission" id="permission" class="form-control">
                <option value="3">SAL</option>
                <option value="1">ADM</option>
                <option value="2">TMLD</option>
            </select>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password" >
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </form>
@endsection

crm/resources/views/backoffice/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Users')

@section('pageHeader', 'Edit Users')

@section('content')
    <form action="{{ route('users.update', $user) }}" method="post">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" id="name" value="{{ $user->name }}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ $user->email }}">
        </div>
        <div class="form-group">
            <label for="permission">Permission</label>
            <select name="permission" id="permission" class="form-control">
                <option value="1">ADM</option>
                <option value="2">TMLD</option>
                <option value="3">SAL</option>
            </select>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </form>
@endsection

crm/resources/views/backoffice/users/index.blade.php
@extends('layouts.app')
@section('title','Users')
@section('pageHeader','All Users')
@section('content')
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Permission</th>
            <th>Created at</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @foreach($users as$user)
                <tr>
                    <td>{{$user->id}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>
                        @if($user->role_id=='1')
                            ADM
                        @elseif($user->role_id=='2')
                            TMLD
                        @elseif($user->role_id=='3')
                            SAL
                        @endif
                    </td>
                    <td>{{$user->created_at}}</td>
                    <td>
                        <a href="{{ route('users.show', $user) }}" class="btn btn-info">Show
                            <a href="{{ route('users.edit', $user) }}" class="btn btn-primary">Edit</a>
                            <form action="{{ route('users.destroy', $user) }}" method="post" style="display: inline-block">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

crm/resources/views/backoffice/users/show.blade.php
@extends('layouts.app')

@section('title', 'users')

@section('pageHeader', 'Show User')

@section('content')
    <h3><span class="text-bold">Name:</span> {{ $user->name }}</h3>
    <p><span class="text-bold">Email:</span> {{ $user->email }}</p>
    <p><span class="text-bold">Permission:</span>
        @if($user->role_id=='1')
            ADM
        @elseif($user->role_id=='2')
            TMLD
        @elseif($user->role_id=='3')
            SAL
        @endif</p>
    <div>
        <a href="{{ route('users.edit', $user) }}" class="btn btn-primary">Edit</a>
        <form action="{{ route('users.destroy', $user) }}" method="post" style="display: inline-block">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>

@endsection